name: Build and publish Docker image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build the Docker image
        uses: actions/docker/cli@master
        with:
          args: build --file Dockerfile --tag aws-deploy .

      - name: Tag the Docker image
        uses: actions/docker/tag@master
        with:
          args: aws-deploy slergberg/aws-deploy

      - name: Login to Docker Hub
        uses: actions/docker/login@master
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}

      - name: Publish the image to Docker Hub
        uses: actions/docker/cli@master
        with:
          args: push slergberg/aws-deploy:latest
