name: Build and publish Docker image

on:
  push:
    branches:
      - master

jobs:
  build-and-publish-to-docker-hub-registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build the Docker image
        uses: actions/docker/cli@master
        with:
          args: build --file Dockerfile --tag ${DOCKER_ORGANIZATION_NAME}/${DOCKER_IMAGE_NAME} .
        env:
          DOCKER_ORGANIZATION_NAME: slergberg
          DOCKER_IMAGE_NAME: aws-deploy

      - name: Login to Docker Hub registry
        uses: actions/docker/login@master
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}

      - name: Publish the image to Docker Hub registry
        uses: actions/docker/cli@master
        with:
          args: push ${DOCKER_ORGANIZATION_NAME}/${DOCKER_IMAGE_NAME}:latest
        env:
          DOCKER_ORGANIZATION_NAME: slergberg
          DOCKER_IMAGE_NAME: aws-deploy

  build-and-publish-to-github-package-registry:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Build the Docker image
        uses: actions/docker/cli@master
        with:
          args: build --file Dockerfile --tag ${DOCKER_REGISTRY_URL}/${DOCKER_ORGANIZATION_NAME}/${DOCKER_IMAGE_NAME} .
        env:
          DOCKER_REGISTRY_URL: docker.pkg.github.com
          DOCKER_ORGANIZATION_NAME: slergberg
          DOCKER_IMAGE_NAME: aws-deploy

      - name: Login to GitHub Package registry
        uses: actions/docker/login@master
        env:
          DOCKER_REGISTRY_URL: docker.pkg.github.com
          DOCKER_USERNAME: ${{ secrets.GITHUB_PACKAGE_USERNAME }}

      - name: Publish the image to GitHub Package registry
        uses: actions/docker/cli@master
        with:
          args: push ${DOCKER_REGISTRY_URL}/${DOCKER_ORGANIZATION_NAME}/${DOCKER_IMAGE_NAME}:latest
        env:
          DOCKER_REGISTRY_URL: docker.pkg.github.com
          DOCKER_ORGANIZATION_NAME: slergberg
          DOCKER_IMAGE_NAME: aws-deploy
